### ISSUE TITLE
Example File

### ISSUE THREAD

**Issue by victorsteven** [pilagod/gorm-cursor-paginator#12]
Nice package. Weldone. Please can you add an example that demonstrates how Before and After are used?
Much appreciated.

**Comment by pilagod** [comment]
I have added a new example file at [example/main.go](https://github.com/pilagod/gorm-cursor-paginator/blob/master/example/main.go), you can also check [paginator_test.go](https://github.com/pilagod/gorm-cursor-paginator/blob/master/paginator_test.go) for more details about how each option works, which is demonstrated in each test case. Thanks 😃

**Comment by victorsteven** [comment]
Great. Thanks
