### ISSUE TITLE
GORM v2.0 support?

### ISSUE THREAD

**Issue by nikicc** [pilagod/gorm-cursor-paginator#22]
Hi!

I'm looking for a cursor-based paginator and I've found this project, which I really like. However, we are on GORM v2, while this repo seems to be on v1. Hence, I'm wondering if there are any plans to migrate this to GORM v2.0 (i.e. the one available at https://github.com/go-gorm/gorm)?

Thanks!

**Comment by pilagod** [comment]
Hi @nikicc, so nice to hear from you.

Yes, indeed. I just realized that there is a new version of GORM recently, and for me it is a must to support it. I think this migration can put into v2 milestone together with other improvement. I plan to start doing this maybe in the next few days or weeks.

Stay tuned, I will notify you as soon as possible if there is any progress 🙂

Thanks!
