### ISSUE TITLE
How to use pagination with KSUID package?

### ISSUE THREAD

**Issue by myrtleTree33** [pilagod/gorm-cursor-paginator#56]
Hi,

I am using https://github.com/segmentio/ksuid for IDs.

How can I paginate using this library?  I see that the error `invalid cursor for paginating` is thrown.

**Comment by pilagod** [comment]
I just did a simple cursor encoding/decoding test for ksuid field, and it didn't encounter any problem.

https://github.com/pilagod/gorm-cursor-paginator/blob/a020d772773c3802988c15f6582ac7cd095c2ac6/cursor/encoding_test.go#L21-L34

Cursor is leveraging `encoding/json` library to do encoding/decoding, and I think ksuid already handles it correctly. 

Could you help providing more code details about how you use ksuid in your model? Thanks.

**Comment by pilagod** [comment]
I will close this issue for now. Feel free to re-open it for further discussion 🙌
