### ISSUE TITLE
Using smart select fields

### ISSUE THREAD

**Issue by dschreij** [pilagod/gorm-cursor-paginator#57]
Gorm allows you to provide a different struct for data selection/population, if you provide the struct that specifies the table to select from in `Model()` ([docs](https://gorm.io/docs/advanced_query.html#Smart-Select-Fields)). For instance, on some occasions, I 'enrich' my model structs with composition to allow adding extra meta fields, e.g.

```go
type UserWithPostCount struct {
    User
    PostCount `json:"post_count"`
}

var results *UserWithPostCount
tx := db.Model(User{}).
     Select("users.*, count(*) as post_count").
     Join("posts on users.id = posts.user_id").
     Group("users.id").
     Find(&results)
```
this works in basic Gorm, where post_count will have the value specified in the select statement and the origin table is defined by `Model(User)`.

I hoped the same would be possible with the `Paginate()` function, by passing the `UserWithPostCount` as the destination struct, but if I try this, I get the error that the table "user_with_post_count" does not exist. 

Would it be possible to let the `Model()` or `Table()` call specify the table to query, and not let the destination struct passed to `Paginate()` define this?

**Comment by pilagod** [comment]
Have you tried custom table name or scoping, mentioned in this document?

https://gorm.io/docs/conventions.html#TableName

Underlying the paginator, it will leverage `gorm.Statement` to parse table name from dest model, like the code shown below:

https://github.com/pilagod/gorm-cursor-paginator/blob/f807e66213b074b491dff8cf5e7fc3040f9768df/internal/util/model.go#L8-L14

So I'm hopeful that custom table name or scoping might be helpful.

**Comment by dschreij** [comment]
Using TableName() works! Thank you very much :)
